### ISSUE TITLE
Juat need theortical explination

### ISSUE THREAD

**Issue by Rishav8989** [Elliot-D-Hill/Stefan-problem#1]
sir will you provide me any theoretical reference just need for my college project

**Comment by Elliot-D-Hill** [comment]
I pulled from this [reference](https://www.diva-portal.org/smash/get/diva2:647481/FULLTEXT01.pdf) and this [reference](http://www.sbai.uniroma1.it/pubblicazioni/doc/phd_quaderni/02-1-and.pdf) for that project.

Cheers

**Comment by Rishav8989** [comment]
thank you, you are very helpful
